# 数据库配置
db_host = "10.0.0.1:9000"
db_name = "default"
db_user = "default"
db_password = "123456"
#geo_country = "./GeoLite2-Country.mmdb"
#geo_city = "./GeoLite2-City.mmdb"
#geo_asn = "./GeoLite2-ASN.mmdb"
# 消息队列配置
[mq]
host = "127.0.0.1:1337"
secret = ""
topic = "hachimi"
compression = false
compressionLevel = 6