// Code generated by 'yaegi extract hachimi/pkg/types'. DO NOT EDIT.

//go:build go1.22
// +build go1.22

package symbols

import (
	"hachimi/pkg/types"
	"reflect"
)

func init() {
	Symbols["hachimi/pkg/types/types"] = map[string]reflect.Value{
		// type definitions
		"Http":    reflect.ValueOf((*types.Http)(nil)),
		"Session": reflect.ValueOf((*types.Session)(nil)),
	}
}
